#############################################################################
# Makefile for building: TransAmerica
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Jan 14 18:59:33 2014
# Project:  TransAmerica.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile TransAmerica.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Brett.cpp \
		City.cpp \
		Game.cpp \
		KIspieler.cpp \
		Koordinate.cpp \
		Main.cpp \
		Move.cpp \
		MyFirstKI.cpp \
		Poeppel.cpp \
		spielbrett.cpp \
		StateList.cpp \
		testKI.cpp \
		uiexec.cpp \
		Vektor.cpp \
		Verbindung.cpp \
		window.cpp \
		Zustand.cpp moc_spielbrett.cpp \
		moc_StateList.cpp \
		moc_uiexec.cpp \
		moc_window.cpp
OBJECTS       = Brett.o \
		City.o \
		Game.o \
		KIspieler.o \
		Koordinate.o \
		Main.o \
		Move.o \
		MyFirstKI.o \
		Poeppel.o \
		spielbrett.o \
		StateList.o \
		testKI.o \
		uiexec.o \
		Vektor.o \
		Verbindung.o \
		window.o \
		Zustand.o \
		moc_spielbrett.o \
		moc_StateList.o \
		moc_uiexec.o \
		moc_window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TransAmerica.pro
QMAKE_TARGET  = TransAmerica
DESTDIR       = 
TARGET        = TransAmerica

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TransAmerica.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile TransAmerica.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile TransAmerica.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TransAmerica1.0.0 || $(MKDIR) .tmp/TransAmerica1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TransAmerica1.0.0/ && $(COPY_FILE) --parents Brett.h City.h Game.h KIspieler.h Konstant.h Konstant_FlyEurope.h Konstant_Standard.h Koordinate.h Move.h MyFirstKI.h Poeppel.h QKonstanten.h spielbrett.h StateList.h testKI.h uiexec.h Vektor.h Verbindung.h window.h Zustand.h .tmp/TransAmerica1.0.0/ && $(COPY_FILE) --parents Brett.cpp City.cpp Game.cpp KIspieler.cpp Koordinate.cpp Main.cpp Move.cpp MyFirstKI.cpp Poeppel.cpp spielbrett.cpp StateList.cpp testKI.cpp uiexec.cpp Vektor.cpp Verbindung.cpp window.cpp Zustand.cpp .tmp/TransAmerica1.0.0/ && (cd `dirname .tmp/TransAmerica1.0.0` && $(TAR) TransAmerica1.0.0.tar TransAmerica1.0.0 && $(COMPRESS) TransAmerica1.0.0.tar) && $(MOVE) `dirname .tmp/TransAmerica1.0.0`/TransAmerica1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TransAmerica1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_spielbrett.cpp moc_StateList.cpp moc_uiexec.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_spielbrett.cpp moc_StateList.cpp moc_uiexec.cpp moc_window.cpp
moc_spielbrett.cpp: Konstant.h \
		Konstant_Standard.h \
		Zustand.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		window.h \
		Game.h \
		Move.h \
		KIspieler.h \
		StateList.h \
		spielbrett.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) spielbrett.h -o moc_spielbrett.cpp

moc_StateList.cpp: Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		StateList.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) StateList.h -o moc_StateList.cpp

moc_uiexec.cpp: window.h \
		Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		Game.h \
		Move.h \
		KIspieler.h \
		StateList.h \
		uiexec.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) uiexec.h -o moc_uiexec.cpp

moc_window.cpp: Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		Game.h \
		Move.h \
		KIspieler.h \
		StateList.h \
		window.h \
		window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Brett.o: Brett.cpp Brett.h \
		Konstant.h \
		Konstant_Standard.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Brett.o Brett.cpp

City.o: City.cpp City.h \
		Konstant.h \
		Konstant_Standard.h \
		Vektor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o City.o City.cpp

Game.o: Game.cpp Game.h \
		Brett.h \
		Konstant.h \
		Konstant_Standard.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Zustand.h \
		Poeppel.h \
		Move.h \
		KIspieler.h \
		StateList.h \
		window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cpp

KIspieler.o: KIspieler.cpp KIspieler.h \
		Konstant.h \
		Konstant_Standard.h \
		Move.h \
		Verbindung.h \
		Vektor.h \
		Koordinate.h \
		City.h \
		Zustand.h \
		Brett.h \
		Poeppel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o KIspieler.o KIspieler.cpp

Koordinate.o: Koordinate.cpp Koordinate.h \
		Konstant.h \
		Konstant_Standard.h \
		City.h \
		Vektor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Koordinate.o Koordinate.cpp

Main.o: Main.cpp uiexec.h \
		window.h \
		Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		Game.h \
		Move.h \
		KIspieler.h \
		StateList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

Move.o: Move.cpp Move.h \
		Konstant.h \
		Konstant_Standard.h \
		Verbindung.h \
		Vektor.h \
		Koordinate.h \
		City.h \
		Zustand.h \
		Brett.h \
		Poeppel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Move.o Move.cpp

MyFirstKI.o: MyFirstKI.cpp MyFirstKI.h \
		KIspieler.h \
		Konstant.h \
		Konstant_Standard.h \
		Move.h \
		Verbindung.h \
		Vektor.h \
		Koordinate.h \
		City.h \
		Zustand.h \
		Brett.h \
		Poeppel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyFirstKI.o MyFirstKI.cpp

Poeppel.o: Poeppel.cpp Poeppel.h \
		Vektor.h \
		Konstant.h \
		Konstant_Standard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Poeppel.o Poeppel.cpp

spielbrett.o: spielbrett.cpp spielbrett.h \
		Konstant.h \
		Konstant_Standard.h \
		Zustand.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		window.h \
		Game.h \
		Move.h \
		KIspieler.h \
		StateList.h \
		QKonstanten.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spielbrett.o spielbrett.cpp

StateList.o: StateList.cpp StateList.h \
		Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StateList.o StateList.cpp

testKI.o: testKI.cpp testKI.h \
		KIspieler.h \
		Konstant.h \
		Konstant_Standard.h \
		Move.h \
		Verbindung.h \
		Vektor.h \
		Koordinate.h \
		City.h \
		Zustand.h \
		Brett.h \
		Poeppel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testKI.o testKI.cpp

uiexec.o: uiexec.cpp uiexec.h \
		window.h \
		Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		Game.h \
		Move.h \
		KIspieler.h \
		StateList.h \
		testKI.h \
		MyFirstKI.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o uiexec.o uiexec.cpp

Vektor.o: Vektor.cpp Vektor.h \
		Konstant.h \
		Konstant_Standard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vektor.o Vektor.cpp

Verbindung.o: Verbindung.cpp Verbindung.h \
		Vektor.h \
		Konstant.h \
		Konstant_Standard.h \
		Koordinate.h \
		City.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Verbindung.o Verbindung.cpp

window.o: window.cpp window.h \
		Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h \
		Game.h \
		Move.h \
		KIspieler.h \
		StateList.h \
		spielbrett.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

Zustand.o: Zustand.cpp Zustand.h \
		Konstant.h \
		Konstant_Standard.h \
		Brett.h \
		Koordinate.h \
		City.h \
		Vektor.h \
		Verbindung.h \
		Poeppel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Zustand.o Zustand.cpp

moc_spielbrett.o: moc_spielbrett.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spielbrett.o moc_spielbrett.cpp

moc_StateList.o: moc_StateList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StateList.o moc_StateList.cpp

moc_uiexec.o: moc_uiexec.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_uiexec.o moc_uiexec.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

